### ISSUE TITLE
Create database from ISDB

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/dereplication#1]
Create the full database as a JSON from the data present on ISDB

In the ZIP you have the mgf files and the csv files. You can first merge them with the proposed bash script.

The csv file can be parse using 'papaparse'.
After the extra meta information present in the CSV should be added to the MGF file.

Once everything is combined the data should be saved as a JSON.

**Comment by opatiny** [comment]
Where are the files?

**Comment by opatiny** [comment]
ISBD: http://oolonek.github.io/ISDB/

**Comment by opatiny** [comment]
To combine the csv files in ISDB, run `./merge_db.sh`.

To combine the mgf files, use `cat *.mgf   >>  UNDP_ISDB.mgf`.

**Comment by opatiny** [comment]
Done. Resulting data is in `dereplication/data`. Script used to generate it is `dereplication/data/predicted/generatePredictions.js`.
