### ISSUE TITLE
Check that all the experimental products are in the reference DB

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/dereplication#3]

**Comment by opatiny** [comment]
We append the `idCode` and the `idCodeNoStereo` to each entry of `experiments.json` and `predictions.json` using `openchemlib`. We can then use `idCodeNoStereo` to verify if all entries of `experiments.json` have a match in the predictions.

The script is `data/checkData.js`.

**Comment by opatiny** [comment]
On 2020.04.07 9:30 AM, we have 782 experimental spectra with a match in predictions.
