### ISSUE TITLE
Calculate the similarity between 2 entries

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/dereplication#5]
Make a method that allows to calculate the similarity between 2 entries

- align the 2 (x:[], y:[]} and take only the common one
- if less than X common, return 0
- sum to 1 of y1 and y2
- return cosine similarity: https://github.com/mljs/distance

We could give the algorithm to calculate the distance as an option (the option is the function that accepts the 2 vectors)

**Comment by opatiny** [comment]
`src/similarity.js`
