### ISSUE TITLE
Calculate the position of the best match

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/dereplication#6]
For the 10 first experimental entries calculate the similarity will all the references and find the position of the exact match.

Because there will be a sort you should only keep the one that has a similarity >= 0.7. 

So you create a new array that contains objects like
- sample
- references: [{similarity: 0.9, reference}] but you only add elements in this array if similarity is over 0.9
- matchPosition (calculated based on the references after sorting and checking where the reference=sample)

**Comment by opatiny** [comment]
Wrote the function `computeSimilarities()` which does that.

However the results are really bad ( with a `matchIndex` between 4000 and 100000)...

First tests were done on the 2020.04.08, in commit 3b83ab2378aa5bd1588737a3d0965278ef6ba959.

**Comment by opatiny** [comment]
We define the "position of the best match" as `matchIndex`, which is the position of the exact match in an array with all the predictions, sorted by descending similarity with the experiment.
